# This rule is not used by the project free5gc-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over k8s.startkubernetes.com.my.domain.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: free5gc-controller
    app.kubernetes.io/managed-by: kustomize
  name: free5gc-admin-role
rules:
- apiGroups:
  - k8s.startkubernetes.com.my.domain
  resources:
  - free5gcs
  verbs:
  - '*'
- apiGroups:
  - k8s.startkubernetes.com.my.domain
  resources:
  - free5gcs/status
  verbs:
  - get
